version: '2'
volumes:
  config:
  build:
  node_modules:
services:
   db:
     image: mysql:latest
     volumes:
       - ./.db:/var/lib/mysql
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: ${JDBC_PASSWORD}
       MYSQL_DATABASE: ${JDBC_DB}
       MYSQL_USER: ${JDBC_USER}
       MYSQL_PASSWORD: ${JDBC_PASSWORD}
